#!/bin/sh

APP=$(basename $0)
_appdir=$(dirname $0)
TOP=$(realpath $(cd $_appdir/../../.. && pwd))

export TOP

action="$1" && shift
role="$1" && shift

conf=""
if [ ! -z "$CONF" ]; then
    if [ -f "$CONF" ]; then
	conf="$CONF"
    fi
fi

if [ -z "$role" ]; then
    echo "no role specified"
    exit 1
fi

. $TOP/share/sc/lib/funcs
. $TOP/share/sc/sv/svcs

load_conf "$TOP/etc/sc.conf.default"

if [ ! -z "$conf" ]; then
    if [ -f "$conf" ]; then
	load_conf "$conf"
    fi
fi

check_debug

if [ -f $TOP/share/sc/roles/$role ]; then
    . $TOP/share/sc/roles/$role
else
    echo role "$role" can not be found
    exit 1
fi

if [ "x$(fn_defined role_${role}_${action})" = "xyes" ]; then
    eval "role_${role}_${action} $@"
fi

# Local Variables:
# mode: sh
# End:
