#!/usr/local/bin/expect -f
set user [lindex $argv 0]
set pass [lindex $argv 1]
set users [lrange $argv 2 end]
set timeout -1

spawn cyradm -u $user localhost
expect -re "^.*assword:"
send "$pass\r"

expect -re "^.*>"

foreach user $users {
   send "cm user/$user\r"
   expect -re "^.*>"
}

send "exit\r"
expect eof
